# # DYNAMIC CONFIGURATION
http:
  # routers:
  #   nginx:
  #     rule: Host(`nginx.localhost`)
  #     entrypoints:
  #     - web
  #     middlewares:
  #     - redirect-to-https
  # middlewares:
  #   redirect-to-https:
  #     redirectScheme:
  #       scheme: https
  #       permanent: false